[build-system]
requires = ["uv_build>=0.9.21,<=1.0.0"]
build-backend = "uv_build"

[project]
name = "netcheck"
description = "netcheck : Check network connectivity"
authors = [{ name = "Gene C", email = "arch@sapience.com" }]
license = "GPL-2.0-or-later"
readme = "README.rst"
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
requires-python = ">=3.13"
version = "1.10.0"
dependencies = []

[project.urls]
Documentation = "https://github.com/gene-git/netcheck/Docs"
Issues = "https://github.com/gene-git/netcheck/issues"
Source = "https://github.com/gene-git/netcheck"

[tool.uv.build-backend]
module-name = 'netcheck_mod'
module-root = "src"
source-include = [
    '/netcheck_mod',
    '/netcheck_mod/py.typed',
]
source-exclude = [
    ".pytest_cache",
    "__pycache__",
    ".mypy_cache",
]

[tool.mypy]
check_untyped_defs = true
follow_untyped_imports = true

