#!/usr/bin/bash
#
# Source code checks.
# 

export PYTHONPATH=(/usr/bin/realpath src)
mod="src/netcheck_mod"

/usr/bin/pylint "$mod"/*.py "$mod"/*/*.py
/usr/bin/pycodestyle --max-line-length=110 "$mod"/*.py "$mod"/*/*.py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports "$mod"


